"""sequence-deployments-projects

Revision ID: 4cf2ba8715d2
Revises: 58e367bdda57
Create Date: 2022-11-21 09:18:25.157319

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "4cf2ba8715d2"
down_revision = "58e367bdda57"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deploymenttemplatesequencecorrespondance",
        sa.Column("deployment_id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["deployments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templatesequence.id"],
        ),
        sa.PrimaryKeyConstraint("deployment_id", "template_id"),
    )
    op.add_column("deployments", sa.Column("height", sa.Float(), nullable=True))
    op.add_column(
        "deployments",
        sa.Column("support", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "deployments",
        sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_constraint("deployments_template_sequence_id_fkey", "deployments", type_="foreignkey")
    op.drop_column("deployments", "template_sequence_id")
    op.add_column("devices", sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("files", sa.Column("treated", sa.Boolean(), nullable=False))
    op.add_column(
        "projects",
        sa.Column("protocol", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("acquisition_framework", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("referential", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("timezone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_column("projects", "status")
    op.drop_column("projects", "protocole")
    op.drop_column("projects", "description")
    op.add_column("templatesequence", sa.Column("frequency", sa.Integer(), nullable=False))
    op.drop_column("templatesequence", "frequence")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "templatesequence",
        sa.Column("frequence", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("templatesequence", "frequency")
    op.add_column(
        "projects",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("protocole", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("projects", "image")
    op.drop_column("projects", "timezone")
    op.drop_column("projects", "referential")
    op.drop_column("projects", "acquisition_framework")
    op.drop_column("projects", "protocol")
    op.drop_column("files", "treated")
    op.drop_column("devices", "image")
    op.add_column(
        "deployments",
        sa.Column("template_sequence_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "deployments_template_sequence_id_fkey",
        "deployments",
        "templatesequence",
        ["template_sequence_id"],
        ["id"],
    )
    op.drop_column("deployments", "image")
    op.drop_column("deployments", "support")
    op.drop_column("deployments", "height")
    op.drop_table("deploymenttemplatesequencecorrespondance")
    # ### end Alembic commands ###
