"""Added image to sites

Revision ID: 999aa6bb1fc9
Revises: 4cf2ba8715d2
Create Date: 2024-04-24 11:03:35.912205

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "999aa6bb1fc9"
down_revision = "4cf2ba8715d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sites", sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sites", "image")
    # ### end Alembic commands ###
