library(shiny)
library(dplyr)
library(readr)
library(tidyr)
library(shinyWidgets)
library(lubridate)
library(ggplot2)
library(data.table)
library(vegan)
library(camtrapR)
library(overlap)
library(rlang)
library(tidyverse)

source("R/data.R")
source("R/mod_data_prep.R")
#source("R/analysis/mod_monitoring.R")
#source("R/analysis/mod_species.R")
#source("R/analysis/mod_community.R")
source("R/mod_display_params.R")
source("R/mod_monitoring.R")
source("R/mod_species.R")
source("R/mod_community.R")
source("R/mod_activity.R")
source("R/sample_historic.R")
source("R/barplot_compo_com.R")
source("R/richness_index.R")
source("R/sampling_numbers.R")
source("R/detection_rate.R")
source("R/plot_EP_species.R")
source("R/activity_model_cross.R")
source("R/calc_activity.R")
source("R/translate.R")
source("R/mod_export.R")

source("ui.R")
source("server.R")

runApp(shinyApp(ui, server), port = 8180, host = "0.0.0.0")